### ISSUE TITLE
No module named apk_parse.apk

### ISSUE THREAD

**Issue by xxfenxx** [dwisiswant0/apkleaks#10]
When i run: `python apkleaks.py -f a.apk `

An error occurred：

```
Traceback (most recent call last):
  File "apkleaks.py", line 2, in <module>
    from apkleaks.apkleaks import apkleaks
  File "/git/apkleaks/apkleaks/apkleaks.py", line 2, in <module>
    from apk_parse.apk import APK
ImportError: No module named apk_parse.apk
```

**Comment by dwisiswant0** [comment]
Hey, please take a look at #7.

**Comment by dwisiswant0** [comment]
Hi @xxfenxx, now APKLeaks is released version 2 (that supports Python3). Please give it try!
