### ISSUE TITLE
Can't able to run apkleaks.py

### ISSUE THREAD

**Issue by YashGoti** [dwisiswant0/apkleaks#16]
Getting following Error first
```
Traceback (most recent call last):
  File "apkleaks.py", line 2, in <module>
    from apkleaks.apkleaks import APKLeaks
  File "/mnt/f/InfoSec/Tools/apkleaks/apkleaks/apkleaks.py", line 2, in <module>
    from apkleaks.colors import clr
ImportError: No module named colors
```

**Comment by dwisiswant0** [comment]
Make sure you run with Python3 environment.

**Comment by YashGoti** [comment]
Okay

Script stop at
```
Can't find jadx binary.
Do you want to download jadx? (Y/n) Y
** Downloading jadx...
```

**Comment by dwisiswant0** [comment]
That's because you don't have `jadx` binary on your environment, try to wait if you choose to download jadx on decompiling process.
