### ISSUE TITLE
Porting code to Python3

### ISSUE THREAD

**Issue by dwisiswant0** [dwisiswant0/apkleaks#5]

**Comment by xxa1e** [comment]
Is there a specific library this project relies on that is only available in Python 2? Just started reviewing this project.

**Comment by GanbaruTobi** [comment]
(apkleaks) ➜  apkleaks git:(master) python apkleaks.py
Traceback (most recent call last):
  File "/home/gbaru/Downloads/apkleaks/apkleaks.py", line 2, in <module>
    from apkleaks.apkleaks import apkleaks
  File "/home/gbaru/Downloads/apkleaks/apkleaks/apkleaks.py", line 2, in <module>
    from apk_parse.apk import APK
  File "/home/gbaru/.virtualenvs/apkleaks/lib/python3.9/site-packages/apk_parse/apk.py", line 1582
    except Exception, why:
