### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 62 column 1 (char 4619)

### ISSUE THREAD

**Issue by majidmc2** [dwisiswant0/apkleaks#52]
I ran apkleaks with this command:
`sudo python3 apkleaks.py -f ../myapp.apk`
but I got this error:

`
** Decompiling APK...
ERROR - Incorrect arguments: File not found /usr/share/jadx/bin/../myapp.apk

** Scanning against 'com.flightio.app'

** Done with nothing. ¯\_(ツ)_/¯
Traceback (most recent call last):
  File "/home/majidmc2/Desktop/apkleaks/apkleaks.py", line 5, in <module>
    main()
  File "/home/majidmc2/Desktop/apkleaks/apkleaks/cli.py", line 36, in main
    init.scanning()
  File "/home/majidmc2/Desktop/apkleaks/apkleaks/apkleaks.py", line 124, in scanning
    regex = json.load(regexes)
  File "/usr/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 62 column 1 (char 4619)
`

**Comment by w4h4z** [comment]
same here

**Comment by kmskrishna** [comment]
same issue,

**Comment by mlniang** [comment]
Removing the comma at the end of the last line in regexes.json file solved this issue for me.

**Comment by azerpas** [comment]
Still getting this issue with the Docker image
