### ISSUE TITLE
无法使用，提示PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'C:\\Users\\Gao\\AppData\\Local\\Temp\\apkleaks-j3w0yo1j.txt'

### ISSUE THREAD

**Issue by 480840342** [dwisiswant0/apkleaks#94]
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'C:\\Users\\Gao\\AppData\\Local\\Temp\\apkleaks-j3w0yo1j.txt'

PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'C:\\Users\\Gao\\AppData\\Local\\Temp\\apkleaks-j3w0yo1j.txt'

运行：

D:\Gao\工具\安全相关\移动安全\apkleaks>python apkleaks.py -f H5c.apk
     _    ____  _  ___               _
    / \  |  _ \| |/ / |    ___  __ _| | _____
   / _ \ | |_) | ' /| |   / _ \/ _` | |/ / __|
  / ___ \|  __/| . \| |__|  __/ (_| |   <\__ \
 /_/   \_\_|   |_|\_\_____\___|\__,_|_|\_\___/
 v2.6.3
 --
 Scanning APK file for URIs, endpoints & secrets
 (c) 2020-2024, dwisiswant0

** Decompiling APK...
文件名、目录名或卷标语法不正确。

** Scanning against 'plus.H5C45293A'
Traceback (most recent call last):
  File "D:\Gao\工具\安全相关\移动安全\apkleaks\apkleaks.py", line 5, in <module>
    main()
  File "D:\Gao\工具\安全相关\移动安全\apkleaks\apkleaks\cli.py", line 41, in main
    init.cleanup()
  File "D:\Gao\工具\安全相关\移动安全\apkleaks\apkleaks\apkleaks.py", line 148, in cleanup
    os.remove(self.output)
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'C:\\Users\\Gao\\AppData\\Local\\Temp\\apkleaks-j3w0yo1j.txt'
版本 v2.63

**Comment by zmxw** [comment]
中文目录 不行

**Comment by jia7589333-alt** [comment]
换了不是中文目录也不行

**Comment by nocultrue** [comment]
我也遇到了  请问解决了吗

**Comment by 480840342** [comment]
> 我也遇到了 请问解决了吗

忘记了，好像就是不要用中文目录就好

**Comment by FahidAltahraw** [comment]
English please

في الجمعة، ١٥ أغسطس ٢٠٢٥، ١١:٣٤ ص 480840342 ***@***.***> كتب:

**Comment by 0xbartita** [comment]
Anyone solved this ?
